# generated by make process
# .clang-format
# .travis.yml
# CHANGELOG.md
# LICENSE
# README.md
# appveyor.yml
# configure.bat
# docs/README.md
# include/dimcli/cli.h
# src/cli.cpp
# tests/cli/clitest.cpp
# tests/cli/pch.cpp
# tests/cli/pch.h
# tests/perf/args.h
# tests/perf/pch.cpp
# tests/perf/pch.h
# tests/perf/perftest.cpp
