# generated by make process
# .clang-format
# LICENSE
# README.md
# appveyor.yml
# docs/README.md
# docs/build.bat
# docs/friendly.css
# docs/index.erb
# docs/index.html
# docs/readme.md.html
# docs/strapdown.css
# docs/strapdown.js
