# Copyright Glen Knowles 2025.
# Distributed under the Boost Software License, Version 1.0.
#
# .circleci/build-codecov.yml

# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@5.4.3

workflows:
  build:
    jobs:
      - build-dunix:
          env: CXX=g++ CC=gcc GCOV=gcov BUILD_COVERAGE=ON
          image: gcc
          config: Debug
          coverage: true

jobs:
  build-dunix:
    parameters:
      image: {type: string}
      env: {type: string}
      config: {type: string}
      coverage: {type: boolean, default: false}
    docker:
      - image: <<parameters.image>>
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install
          command: |
            export <<parameters.env>>
            apt-get update -y
            apt-get install cmake -y
            apt-get install locales-all -y
      - run:
          name: Build
          command: |
            export <<parameters.env>>
            mkdir -p build && cd build
            cmake .. -DBUILD_COVERAGE:BOOL=${BUILD_COVERAGE}
            cmake --build . --config <<parameters.config>>
      - run:
          name: Test
          command: |
            export <<parameters.env>>
            LANG=en_US.UTF-8
            export COLUMNS=80
            cd bin
            ./cli --test
      - when:
          condition: <<parameters.coverage>>
          steps:
            - codecov/upload
