# Copyright Glen Knowles 2025.
# Distributed under the Boost Software License, Version 1.0.
#
# .circleci/config.yml

# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  build-msvc:
    jobs:
      - build-win:
          image: windows-server-2019-vs2019:current
          generator: "Visual Studio 16 2019"
          matrix:
            parameters:
              platform: [Win32, x64]
              config: [Debug, Release]
              toolset: [v140, v141]
      - build-win:
          image: windows-server-2022-gui:current
          generator: "Visual Studio 17 2022"
          matrix:
            parameters:
              platform: [Win32, x64]
              config: [Debug, Release]
              toolset: [v142, v143]

jobs:
  build-win:
    parameters:
      image: {type: string}
      generator: {type: string}
      platform: {type: string}
      config: {type: string}
      toolset: {type: string}
    environment:
      p_generator: <<parameters.generator>>
      p_platform: <<parameters.platform>>
      p_config: <<parameters.config>>
      p_toolset: <<parameters.toolset>>
    machine:
      image: <<parameters.image>>
      resource_class: windows.medium
      shell: cmd.exe
    steps:
      - checkout
      - run:
          name: Build
          command: cd .circleci && build-win
      - run:
          name: Test
          command: cd bin && cli --test --verbose
