# Copyright Glen Knowles 2025.
# Distributed under the Boost Software License, Version 1.0.
#
# .circleci/circle-clang.yml

# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  build-clang:
    jobs:
      - build-dunix:
          env: CXX=clang++ CC=clang
          matrix:
            parameters:
              image:
                - silkeh/clang:11
                - silkeh/clang:12
                - silkeh/clang:13
                - silkeh/clang:14
                - silkeh/clang:15
                - silkeh/clang:16
                - silkeh/clang:17
                - silkeh/clang:18
                - silkeh/clang:19
                - silkeh/clang:20
              config: [Debug, Release]

jobs:
  build-dunix:
    parameters:
      image: {type: string}
      env: {type: string}
      config: {type: string}
      coverage: {type: boolean, default: false}
    docker:
      - image: <<parameters.image>>
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install
          command: |
            export <<parameters.env>>
            apt-get update -y
            apt-get install cmake -y
            apt-get install locales-all -y
      - run:
          name: Build
          command: |
            export <<parameters.env>>
            mkdir -p build && cd build
            cmake .. -DBUILD_COVERAGE:BOOL=${BUILD_COVERAGE}
            cmake --build . --config <<parameters.config>>
      - run:
          name: Test
          command: |
            export <<parameters.env>>
            LANG=en_US.UTF-8
            export COLUMNS=80
            cd bin
            ./cli --test
