# Copyright Glen Knowles 2025.
# Distributed under the Boost Software License, Version 1.0.
#
# .circleci/config.yml

# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ &
# https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build-win:
          image: windows-server-2019-gui:current
          generator: Visual Studio 16 2019
          matrix:
            parameters:
              platform: [Win32, x64]
              configuration: [Debug, Release]
              toolset: [v140, v141]
      - build-win:
          matrix:
            parameters:
              image: [windows-server-2022-gui:current]
              generator: [Visual Studio 17 2022]
              platform: [Win32, x64]
              configuration: [Debug, Release]
              toolset: [v142, v143]

jobs:
  build-win:
    parameters:
      image: {type: string}
      generator: {type: string}
      platform: {type: string}
      configuration: {type: string}
      toolset: {type: string}

    # Specify the execution environment.
    # https://circleci.com/docs/configuration-reference/#executor-job
    machine:
      image: <<parameters.image>>
      shell: cmd

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview &
    # https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout

      - run:
          name: Build
          command: |
            md build
            cd build
            cmake .. -G "<<parameters.generator>>" -A <<parameters.platform>>^
              -T <<parameters.toolset>>
            cmake . -DCMAKE_BUILD_TYPE=<<parameters.configuration>>^
              -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON
            cmake --build . --target install^
              --config <<parameters.configuration>>

      - run:
          name: Test
          command: '"bin/cli" --test'
