version: 2.1

workflows:
  build:
    jobs:
      - build-win:
          matrix:
            parameters:
              image: [windows-server-2019-gui:current]
              generator: [Visual Studio 16 2019]
              platform: [Win32, x64]
              configuration: [Debug, Release]
              toolset: [v140, v141]
      - build-win:
          matrix:
            parameters:
              image: [windows-server-2022-gui:current]
              generator: [Visual Studio 17 2022]
              platform: [Win32, x64]
              configuration: [Debug, Release]
              toolset: [v142, v143]

jobs:
  build-win:
    parameters:
      image: {type: string}
      generator: {type: string}
      platform: {type: string}
      configuration: {type: string}
      toolset: {type: string}
    machine:
      image: <<parameters.image>>
      resource_class: medium
      shell: cmd
    steps:
      - checkout
      - run:
          name: Build
          command: |
            md build
            cd build
            cmake .. -G "<<parameters.generator>>" -A <<parameters.platform>>^
              -T <<parameters.toolset>>
            cmake . -DCMAKE_BUILD_TYPE=<<parameters.configuration>>^
              -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON
            cmake --build . --target install --config <<parameters.configuration>>
      - run:
          name: Test
          command: '"bin/cli" --test'
