# generated by make process
# ../include/dim/cli.h
# ../include/dim/config.h
# ../include/dim/config_suffix.h
# ../include/dim/console.h
# ../include/dim/util.h
# argv.cpp
# cli.cpp
# console.cpp
# pch.cpp
# pch.h
